### ISSUE TITLE
Error from create-nginx.yml:   error while evaluating conditional (deploy and deploy.status.replicas == deploy.status.get(\"availableReplicas\", 0)): 'dict object' has no attribute 'replicas'"

### ISSUE THREAD

**Issue by jwmatthews** [fusor/ocp-velero-ansible#5]
Ran into below with MacOS

$ ansible-playbook create-nginx.yml 
 [WARNING]: Unable to parse /etc/ansible/hosts as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [localhost] ************************************************************************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************************************************
ok: [localhost]

TASK [install_ark : create ark dir] *****************************************************************************************************************************************
ok: [localhost]

TASK [install_ark : get ark] ************************************************************************************************************************************************
ok: [localhost]

TASK [login_ocp : debug] ****************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "Logging into cluster using KUBECONFIG: /git/jwmatthews/ocp-velero-ansible/auth/kubeconfig"
}

TASK [login_ocp : login to cluster] *****************************************************************************************************************************************
changed: [localhost]

TASK [create_nginx_app_with_backup : Create Nginx application] **************************************************************************************************************
changed: [localhost]

TASK [create_nginx_app_with_backup : Wait 2 minutes for nginx deployment] ***************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The conditional check 'deploy and deploy.status.replicas == deploy.status.get(\"availableReplicas\", 0)' failed. The error was: error while evaluating conditional (deploy and deploy.status.replicas == deploy.status.get(\"availableReplicas\", 0)): 'dict object' has no attribute 'replicas'"}
	to retry, use: --limit @/git/jwmatthews/ocp-velero-ansible/create-nginx.retry

PLAY RECAP ******************************************************************************************************************************************************************
localhost                  : ok=6    changed=2    unreachable=0    failed=1

**Comment by jwmatthews** [comment]
Waited a few minutes and re-ran create-nginx.yml and saw it get past the 'deploy' successfully.

Now it's failing on the backup piece:

fatal: [localhost]: FAILED! => {
    "attempts": 10, 
    "backup": {
        "apiVersion": "ark.heptio.com/v1", 
        "kind": "Backup", 
        "metadata": {
            "creationTimestamp": "2019-02-12T02:00:39Z", 
            "generation": 1, 
            "labels": {
                "ark.heptio.com/storage-location": "default"
            }, 
            "name": "nginx-backup", 
            "namespace": "heptio-ark", 
            "resourceVersion": "180092", 
            "selfLink": "/apis/ark.heptio.com/v1/namespaces/heptio-ark/backups/nginx-backup", 
            "uid": "fee198cf-2e69-11e9-a839-0af95ee3886e"
        }, 
        "spec": {
            "includedNamespaces": [
                "*"
            ], 
            "labelSelector": {
                "matchLabels": {
                    "app": "nginx"
                }
            }, 
            "storageLocation": "default", 
            "ttl": "720h0m0s"
        }, 
        "status": {
            "completionTimestamp": "2019-02-12T02:00:52Z", 
            "expiration": "2019-03-14T02:00:39Z", 
            "phase": "Failed", 
            "startTimestamp": "2019-02-12T02:00:39Z", 
            "version": 1
        }
    }
}

**Comment by alexander-demicev** [comment]
I have the same error https://github.com/fusor/ocp-velero-ansible/issues/5#issue-409076101

**Comment by dymurray** [comment]
@jwmatthews For more information on why the backup failed it is useful to get the logs of the `ark` pod in namespace `heptio-ark`. The information on that resource doesn't really give us enough info to know why the backup failed.

In reference to the deployment failure... seems like it's failing because while the pods come up `status` doesn't have `replicas` as a dict object yet. We might need to add some logic to catch that.

**Comment by djwhatle** [comment]
@dymurray i think we might be able to fix this by tweaking the logic in the role slightly.

https://github.com/fusor/ocp-velero-ansible/blob/master/roles/create_nginx_app_with_backup/tasks/main.yml

Currently, the `until` section looks like this:
```
until: deploy and deploy.status.replicas == deploy.status.get("availableReplicas", 0)
```
Note how there's a jump from `deploy` to `deploy.status.replicas` without checking that `status` exists.

If we were to rewrite like so:
```
until: deploy and deploy.status and deploy.status.replicas == deploy.status.get("availableReplicas", 0)
```

I believe we wouldn't have the issue. This would work as long as Ansible stops evaluating "and" expressions at the first "Falsey" part of the expression.

__Edit__
After reading the additional comments here more closely, I don't think this would necessarily work 👎

**Comment by djwhatle** [comment]
I believe I've fixed this in https://github.com/fusor/ocp-velero-ansible/pull/7

**Comment by dymurray** [comment]
Closing since #7 should resolve this.
